### ISSUE TITLE
Change signature of closure to use Result type

### ISSUE THREAD

**Issue by edorphy** [SagarSDagdu/SDBeaconScanner#2]
Since this framework uses closures instead of structured concurrency, I would highly recommend that you change the closure signature to use the Swift Result type. 

from:
public typealias BeaconScanningCompletion = ([Beacon], Error?) -> Void

to:
public typealias BeaconScanningCompletion = (Result<[Beacon], BeaconErrorType>) -> Void

Why? Smart API signatures that do not inherit legacy objective-c style. 

Either you should have beacons, or you should have an error. This also lets you constrain the error type so you don't need to typecast in your error handling code. It is really, beacons, or a specific domain error that you control.

**Comment by SagarSDagdu** [comment]
Hi @edorphy, thanks for the inputs! I will surely consider your suggestions in the next release. 👍🏻
